// Generic time zones not included in @vvo/tzdb that we want to support
export const genericTimeZones = [
  {
    name: 'Etc/GMT',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: 0,
    abbreviation: 'Etc/GMT',
    rawFormat: '',
    currentTimeOffsetInMinutes: 0,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+0',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: 0,
    abbreviation: 'Etc/GMT+0',
    rawFormat: '',
    currentTimeOffsetInMinutes: 0,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+1',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -60,
    abbreviation: 'Etc/GMT+1',
    rawFormat: '',
    currentTimeOffsetInMinutes: -60,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+2',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -120,
    abbreviation: 'Etc/GMT+2',
    rawFormat: '',
    currentTimeOffsetInMinutes: -120,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+3',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -180,
    abbreviation: 'Etc/GMT+3',
    rawFormat: '',
    currentTimeOffsetInMinutes: -180,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+4',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -240,
    abbreviation: 'Etc/GMT+4',
    rawFormat: '',
    currentTimeOffsetInMinutes: -240,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+5',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -300,
    abbreviation: 'Etc/GMT+5',
    rawFormat: '',
    currentTimeOffsetInMinutes: -300,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+6',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -360,
    abbreviation: 'Etc/GMT+6',
    rawFormat: '',
    currentTimeOffsetInMinutes: -360,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+8',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -480,
    abbreviation: 'Etc/GMT+8',
    rawFormat: '',
    currentTimeOffsetInMinutes: -480,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+9',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -540,
    abbreviation: 'Etc/GMT+9',
    rawFormat: '',
    currentTimeOffsetInMinutes: -540,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+10',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -600,
    abbreviation: 'Etc/GMT+10',
    rawFormat: '',
    currentTimeOffsetInMinutes: -600,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+11',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -660,
    abbreviation: 'Etc/GMT+11',
    rawFormat: '',
    currentTimeOffsetInMinutes: -660,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+12',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -720,
    abbreviation: 'Etc/GMT+11',
    rawFormat: '',
    currentTimeOffsetInMinutes: -720,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT+12',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: -720,
    abbreviation: 'Etc/GMT+11',
    rawFormat: '',
    currentTimeOffsetInMinutes: -720,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-0',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +0,
    abbreviation: 'Etc/GMT-0',
    rawFormat: '',
    currentTimeOffsetInMinutes: +0,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-1',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +60,
    abbreviation: 'Etc/GMT-1',
    rawFormat: '',
    currentTimeOffsetInMinutes: +60,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-2',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +120,
    abbreviation: 'Etc/GMT-2',
    rawFormat: '',
    currentTimeOffsetInMinutes: +120,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-3',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +180,
    abbreviation: 'Etc/GMT-3',
    rawFormat: '',
    currentTimeOffsetInMinutes: +180,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-4',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +240,
    abbreviation: 'Etc/GMT-4',
    rawFormat: '',
    currentTimeOffsetInMinutes: +240,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-5',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +300,
    abbreviation: 'Etc/GMT-5',
    rawFormat: '',
    currentTimeOffsetInMinutes: +300,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-6',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +360,
    abbreviation: 'Etc/GMT-6',
    rawFormat: '',
    currentTimeOffsetInMinutes: +360,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-7',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +420,
    abbreviation: 'Etc/GMT-7',
    rawFormat: '',
    currentTimeOffsetInMinutes: +420,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-8',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +480,
    abbreviation: 'Etc/GMT-8',
    rawFormat: '',
    currentTimeOffsetInMinutes: +480,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-9',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +540,
    abbreviation: 'Etc/GMT-9',
    rawFormat: '',
    currentTimeOffsetInMinutes: +540,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-10',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +600,
    abbreviation: 'Etc/GMT-10',
    rawFormat: '',
    currentTimeOffsetInMinutes: +600,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-11',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +660,
    abbreviation: 'Etc/GMT-11',
    rawFormat: '',
    currentTimeOffsetInMinutes: +660,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-12',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +720,
    abbreviation: 'Etc/GMT-12',
    rawFormat: '',
    currentTimeOffsetInMinutes: +720,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-13',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +780,
    abbreviation: 'Etc/GMT-13',
    rawFormat: '',
    currentTimeOffsetInMinutes: +780,
    currentTimeFormat: '',
    mainCities: []
  },
  {
    name: 'Etc/GMT-14',
    alternativeName: '',
    group: [],
    continentCode: '',
    continentName: '',
    countryName: '',
    countryCode: '',
    rawOffsetInMinutes: +840,
    abbreviation: 'Etc/GMT-14',
    rawFormat: '',
    currentTimeOffsetInMinutes: +840,
    currentTimeFormat: '',
    mainCities: []
  }
];
