export type GuxBlankStateAlignment = 'left' | 'center';
export type GuxBlankStateStatus = 'success' | 'error' | 'info' | 'add';
export type GuxBlankStateBackgroundShape =
  | 'solid-wide'
  | 'solid-narrow'
  | 'gradient-wide'
  | 'gradient-narrow';
export type GuxBlankStateVariant =
  | 'add'
  | 'face-smile'
  | 'success'
  | 'calendar'
  | 'access'
  | 'recording'
  | 'data'
  | 'comments'
  | 'comment'
  | 'comment-question'
  | 'eye'
  | 'magnifying-glass'
  | 'magnifying-glass-question'
  | 'sparkles'
  | 'triangle-exclamation'
  | 'face-disappointed'
  | 'folder-magnifying-glass'
  | 'folder-open'
  | 'file'
  | 'lock'
  | 'message-bot'
  | 'robot'
  | 'message'
  | 'messages'
  | 'cloud'
  | 'article'
  | 'edit'
  | 'connection'
  | 'rectangle-history'
  | 'setting'
  | 'square-dashed'
  | 'square-plus'
  | 'transcription'
  | 'table'
  | 'user'
  | 'user-message'
  | 'users';
