import { EventEmitter, JSX } from '../../../stencil-public-runtime';
export declare class GuxPhoneInput {
  private i18n;
  private inputElement;
  private listboxElement;
  private fieldButtonElement;
  private phoneUtil;
  private numberText;
  root: HTMLElement;
  value: string;
  defaultRegion: string;
  labelId: string;
  hasError: boolean;
  disabled: boolean;
  required: boolean;
  region: string;
  private expanded;
  input: EventEmitter<string>;
  internalError: EventEmitter<boolean>;
  focusSelectedItemAfterRender(expanded: boolean): void;
  private validateValue;
  onInternallistboxoptionsupdated(event: CustomEvent): void;
  onBlur(event: FocusEvent): void;
  onFocus(event: FocusEvent): void;
  onFocusout(event: FocusEvent): void;
  onFocusin(event: FocusEvent): void;
  onClickOutside(): void;
  componentWillLoad(): Promise<void>;
  componentDidRender(): void;
  componentDidLoad(): void;
  componentWillRender(): void;
  private initialValueParse;
  private onInputChange;
  private validatePhoneNumber;
  private phoneNumberUpdated;
  private stopPropagationOfInternalFocusEvents;
  private getOptionElementByValue;
  private fieldButtonClick;
  private collapseListbox;
  private updateRegion;
  private setValidation;
  private setInput;
  private setListBox;
  private renderCountryButton;
  private renderButtonDisplay;
  private renderInput;
  private renderTarget;
  private renderPopup;
  render(): JSX.Element;
}
