import { JSX } from '../../../stencil-public-runtime';
import { GuxClockType, GuxISOHourMinute, GuxMinuteInterval, GuxMinuteStep } from './gux-time-picker.type';
export declare class GuxTimePickerBeta {
  private listElement;
  private clockButton;
  private hourInputElement;
  private minuteInputElement;
  private i18n;
  private valueLastChange;
  private root;
  value: GuxISOHourMinute;
  interval: GuxMinuteInterval;
  step: GuxMinuteStep;
  disabled: boolean;
  required: boolean;
  hasError: boolean;
  clockType: GuxClockType;
  expanded: boolean;
  onFocus(): void;
  onBlur(): void;
  onClickOutside(): void;
  handleKeydown(event: KeyboardEvent): void;
  componentWillLoad(): Promise<void>;
  private updateValue;
  private valueToId;
  private focusRelevantItemInPopupList;
  private toggleDropdown;
  private handleClickDropdownValue;
  private onHourKeyDown;
  private onMinuteKeyDown;
  private onAmPmButtonKeyDown;
  private onListKeyDown;
  private toggleAmPm;
  private getAmPmString;
  private renderNumberInput;
  private renderAmPmSelector;
  private renderClockButton;
  private renderTimeListItems;
  private renderTarget;
  private renderPopup;
  render(): JSX.Element;
}
