#! /usr/bin/env node

const path = require('path');
const fs = require('fs');
const proc = require('child_process');

const srcDir = path.join(__dirname, '../src');
const sourceOutputFile = path.join(__dirname, 'stencil-wrapper.ts');
const typesFile = path.join(srcDir, 'index.d.ts');

const tscPath = require.resolve('.bin/tsc');

proc.execSync(
  `${tscPath} --declaration --emitDeclarationOnly --declarationDir ${srcDir} ${sourceOutputFile}`
);

const autoGeneratedTypes = `
  export * from './components';
  export * from './stencil-wrapper';
`;
fs.writeFileSync(typesFile, autoGeneratedTypes);
