/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GenesysButton {
    /**
    * The component accent (secondary or primary).
    */
    'accent': string;
    /**
    * Indicate if the button is disabled or not
    */
    'disabled': boolean;
    /**
    * The component left icon.
    */
    'leftIcon': string;
    /**
    * The component right icon.
    */
    'rightIcon': string;
    /**
    * The component text.
    */
    'text': string;
  }
  interface GenesysButtonAttributes extends StencilHTMLAttributes {
    /**
    * The component accent (secondary or primary).
    */
    'accent'?: string;
    /**
    * Indicate if the button is disabled or not
    */
    'disabled'?: boolean;
    /**
    * The component left icon.
    */
    'leftIcon'?: string;
    /**
    * The component right icon.
    */
    'rightIcon'?: string;
    /**
    * The component text.
    */
    'text'?: string;
  }

  interface GenesysPaginationButtons {
    'currentPage': number;
    'totalPages': number;
  }
  interface GenesysPaginationButtonsAttributes extends StencilHTMLAttributes {
    'currentPage'?: number;
    'onPageChanged'?: (event: CustomEvent<number>) => void;
    'totalPages'?: number;
  }

  interface GenesysPagination {
    'currentPage': number;
    'itemsPerPage': number;
    'totalItems': number;
  }
  interface GenesysPaginationAttributes extends StencilHTMLAttributes {
    'currentPage'?: number;
    'itemsPerPage'?: number;
    'totalItems'?: number;
  }

  interface GenesysPaginationItemCounts {
    'currentPage': number;
    'itemsPerPage': number;
    'totalItems': number;
  }
  interface GenesysPaginationItemCountsAttributes extends StencilHTMLAttributes {
    'currentPage'?: number;
    'itemsPerPage'?: number;
    'totalItems'?: number;
  }

  interface GenesysToggle {
    /**
    * Indicate if the toggle is checked or not
    */
    'checked': boolean;
    /**
    * Indicate the checked label
    */
    'checkedLabel': string;
    /**
    * Indicate if the toggle is disabled or not
    */
    'disabled': boolean;
    /**
    * Indicate the unchecked label
    */
    'uncheckedLabel': string;
  }
  interface GenesysToggleAttributes extends StencilHTMLAttributes {
    /**
    * Indicate if the toggle is checked or not
    */
    'checked'?: boolean;
    /**
    * Indicate the checked label
    */
    'checkedLabel'?: string;
    /**
    * Indicate if the toggle is disabled or not
    */
    'disabled'?: boolean;
    /**
    * Triggered when the state of the component changed.
    */
    'onCheck'?: (event: CustomEvent) => void;
    /**
    * Indicate the unchecked label
    */
    'uncheckedLabel'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GenesysButton': Components.GenesysButton;
    'GenesysPaginationButtons': Components.GenesysPaginationButtons;
    'GenesysPagination': Components.GenesysPagination;
    'GenesysPaginationItemCounts': Components.GenesysPaginationItemCounts;
    'GenesysToggle': Components.GenesysToggle;
  }

  interface StencilIntrinsicElements {
    'genesys-button': Components.GenesysButtonAttributes;
    'genesys-pagination-buttons': Components.GenesysPaginationButtonsAttributes;
    'genesys-pagination': Components.GenesysPaginationAttributes;
    'genesys-pagination-item-counts': Components.GenesysPaginationItemCountsAttributes;
    'genesys-toggle': Components.GenesysToggleAttributes;
  }


  interface HTMLGenesysButtonElement extends Components.GenesysButton, HTMLStencilElement {}
  var HTMLGenesysButtonElement: {
    prototype: HTMLGenesysButtonElement;
    new (): HTMLGenesysButtonElement;
  };

  interface HTMLGenesysPaginationButtonsElement extends Components.GenesysPaginationButtons, HTMLStencilElement {}
  var HTMLGenesysPaginationButtonsElement: {
    prototype: HTMLGenesysPaginationButtonsElement;
    new (): HTMLGenesysPaginationButtonsElement;
  };

  interface HTMLGenesysPaginationElement extends Components.GenesysPagination, HTMLStencilElement {}
  var HTMLGenesysPaginationElement: {
    prototype: HTMLGenesysPaginationElement;
    new (): HTMLGenesysPaginationElement;
  };

  interface HTMLGenesysPaginationItemCountsElement extends Components.GenesysPaginationItemCounts, HTMLStencilElement {}
  var HTMLGenesysPaginationItemCountsElement: {
    prototype: HTMLGenesysPaginationItemCountsElement;
    new (): HTMLGenesysPaginationItemCountsElement;
  };

  interface HTMLGenesysToggleElement extends Components.GenesysToggle, HTMLStencilElement {}
  var HTMLGenesysToggleElement: {
    prototype: HTMLGenesysToggleElement;
    new (): HTMLGenesysToggleElement;
  };

  interface HTMLElementTagNameMap {
    'genesys-button': HTMLGenesysButtonElement
    'genesys-pagination-buttons': HTMLGenesysPaginationButtonsElement
    'genesys-pagination': HTMLGenesysPaginationElement
    'genesys-pagination-item-counts': HTMLGenesysPaginationItemCountsElement
    'genesys-toggle': HTMLGenesysToggleElement
  }

  interface ElementTagNameMap {
    'genesys-button': HTMLGenesysButtonElement;
    'genesys-pagination-buttons': HTMLGenesysPaginationButtonsElement;
    'genesys-pagination': HTMLGenesysPaginationElement;
    'genesys-pagination-item-counts': HTMLGenesysPaginationItemCountsElement;
    'genesys-toggle': HTMLGenesysToggleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
