#! /usr/bin/env node

const Handlebars = require('handlebars');
const path = require('path');
const fs = require('fs');
const proc = require('child_process');

const CHART_COMPONENT_ASSETS_PATH =
  process.env.CHART_COMPONENT_ASSETS_PATH || '';

console.info(`Wrapping stencil loader.`);
if (CHART_COMPONENT_ASSETS_PATH.length > 0) {
  console.info(`  Embedded CDN URL will be: ${CHART_COMPONENT_ASSETS_PATH}`);
} else {
  console.info(`  No CDN URL specified.`);
}

const tscPath = require.resolve('.bin/tsc');
const templateFile = path.join(__dirname, './stencil-wrapper.ts');
const sourceOutputFolder = path.join(__dirname, '../build');
const sourceOutputFile = path.join(sourceOutputFolder, 'stencil-wrapper.ts');
const distDir = path.join(__dirname, '../dist');
const typesDir = path.join(distDir, 'types');
const typesFile = path.join(typesDir, 'index.d.ts');
const template = Handlebars.compile(fs.readFileSync(templateFile, 'utf8'));

const source = template({
  chart_component_assets_path: CHART_COMPONENT_ASSETS_PATH
});

if (!fs.existsSync(sourceOutputFolder)) {
  fs.mkdirSync(sourceOutputFolder, { recursive: true });
}
fs.writeFileSync(sourceOutputFile, source);

proc.execSync(
  `${tscPath} --target es2017 --moduleResolution node --allowSyntheticDefaultImports --declaration --declarationDir ${typesDir} --outDir ${distDir}  ${sourceOutputFile}`,
  { stdio: 'inherit' }
);

const autoGeneratedTypes = `
  export * from './components';
  export * from './stencil-wrapper';
`;
fs.writeFileSync(typesFile, autoGeneratedTypes);
